version: ‘2’
services:
  web:
    container_name: modeloPHP5.4-Apache
    Build: .
    ports:
      — 8889:80
    volumes:
      — ./www:/var/www/html
    links:
      — db
    db:
    container_name: modeloMySQL
    build:
      context: ./
      dockerfile: DockerfileDB
      volumes:
        — /var/lib/mysql
      ports:
        — 3307:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: dockerdemo