# ./docker-compose.yml
version: '3'

services:
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerdemo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"