# ./docker-compose.yml
version: "3"

services:
  achi-php-apache:
    image: php:7.2.2-apache
    container_name: achi-php-apache
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: 52.15.252.196
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: dockerdemo
    volumes:
      - /src:/var/www/html:rw
    depends_on:
      - achi-mysql
    networks:
      - wp-net
  achi-mysql:
    image: mysql:5.7
    container_name: achi-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerdemo
    networks:
      - wp-net

networks:
  wp-net:
    driver: bridge